server:
  port: 8085

spring:
  application:
    name: hot-reservation-service

  data:
    redis:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}



  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 1ì´ˆ = 1000 (ms)
queue:
  sse:
    ttl: 1200000

redis:
  queue:
    key: "reservation:queue"

  available:
    users:
      key: "reservation:available_users"

  pubsub:
    channel: "waiting-queue"

reservation:
  entry:
    ttl: 600000

  available:
    user:
      limit: 10

  process:
    interval: 4000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

lb:
  dns:
    store: ${LB_DNS_STORE}
