server:
  port: 8085

spring:
  application:
    name: hot-reservation-service

  data:
    redis:
      host: ${CACHE_HOST}
      port: 6379
      username: ${CACHE_USERNAME}
      password: ${CACHE_PASSWORD}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 20분 (1200초) - 대기열 sse 타임아웃 (ms)
queue:
  sse:
    timeout: ${QUEUE.SSE.TIMEOUT}

redis:
  queue:
    key: "reservation:queue"

  token:
    prefix: "reservation:token:"

  available:
    users:
      key: "reservation:available_users"

reservation:
  # 20분 (1200초) - 예약 가능 토큰 최대 유지 시간 (ms)
  token:
    ttl: ${RESERVATION_TOKEN_TTL}

  # 예약 가능 최대 인원
  available:
    user:
      limit: ${RESERVATION_AVAILABLE_USER_LIMIT}

  # 예약 상태 만료 확인 주기 (ms)
  process:
    interval: ${RESERVATION_PROCESS_INTERVAL}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

lb:
  dns:
    store: ${LB_DNS_STORE}
