server:
  port: 8085

spring:
  application:
    name: hot-reservation-service

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  datasource:
    url: jdbc:postgresql://localhost:5433/tk-reservation
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 1ì´ˆ = 1000 (ms)
queue:
  sse:
    ttl: 120000

redis:
  queue:
    key: "reservation:queue"

  available:
    users:
      key: "reservation:available_users"

  pubsub:
    channel: "waiting-queue"

reservation:
  entry:
    ttl: 30000

  available:
    user:
      limit: 50

  process:
    interval: 1000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
