server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

jwt:
  secret: ${JWT_SECRET}

gateway:
  uris:
    review: ${LB_DNS_REVIEW}
    user: ${LB_DNS_USER}
    store: ${LB_DNS_STORE}
    search: ${LB_DNS_SEARCH}
    hot-reservation: ${LB_DNS_HOT_RESERVATION}
    reservation: ${LB_DNS_RESERVATION}
#    waiting: lb://WAITING-SERVICE

# Eureka 클라이언트 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL_DEV}
  instance:
    prefer-ip-address: true

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.tablekok.gateway_service: DEBUG
