spring:
  application:
    name: review-service
  profiles:
    active: prod
  datasource:
    url: ${DB_PROD_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
